[project]
name = "genie"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv>=1.1.1",
    "pyupbit>=0.2.34",
    "pydantic>=2.0.0",
    "pydantic-settings>=2.0.0",
    "pytest>=8.0.0",
    "pandas>=2.0.0",
    "pandas-stubs==2.3.2.250926",
    "requests>=2.31.0",
    "ruff>=0.14.0",
]

[tool.pytest.ini_options]
pythonpath = "."
